/* 无浏览器的逻辑冒烟测试；真实布局/浏览器行为另行验收。 */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=fs.existsSync(path.join(__dirname,'../dist/app.js'))?path.join(__dirname,'../dist'):path.join(__dirname,'..');
let clock=Date.now();const storage=new Map();const element=()=>({innerHTML:'',textContent:'',value:'全部',open:false,style:{setProperty(){}},classList:{add(){},remove(){}},showModal(){this.open=true},close(){this.open=false},querySelectorAll(){return []},click(){}});
const els={'#app':element(),'#toast':element(),'#dialog':element(),'meta[name=theme-color]':element()};
const ctx={console,Date:class extends Date{constructor(...a){super(...(a.length?a:[clock]))}static now(){return clock}},setTimeout:()=>0,clearTimeout(){},setInterval(){},URL,Blob,Math,Map,Set,JSON,Object,Number,Array,String,Error,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},navigator:{},location:{protocol:'file:'},document:{querySelector:s=>els[s]||null,querySelectorAll:()=>[],addEventListener(){},documentElement:{style:{setProperty(){}}},body:{className:''}},addEventListener(){},scrollTo(){}};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['questions.js','engine.js','themes.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
let app=fs.readFileSync(path.join(root,'app.js'),'utf8');app=app.replace('render();\n})();',`window.TEST={get state(){return state},get mode(){return mode},setMode:v=>mode=v,setConfig:c=>Object.assign(config,c),setView:v=>view=v,setSelected:v=>selected=v,current,startSession,submit,next,setQuestion,finish,action,render,validateBackup,pool,openQuestion,importFile};render();\n})();`);vm.runInContext(app,ctx);const T=ctx.TEST;assert(T);
assert.equal(ctx.SHIZHI_BANK.questions.length,2957);assert.equal(ctx.SHIZHI_THEMES.length,26);
for(const v of ['home','practice','review','library','stats','themes','settings']){T.setView(v);T.render();assert(els['#app'].innerHTML.length>500,`${v} renders`);}
T.setMode('sequence');T.setConfig({dept:'运营管理部',from:1,to:30,count:2,type:'全部'});T.startSession();assert.equal(T.state.session.ids.length,2);assert.equal(T.current().dept,'运营管理部');let q=T.current();T.setSelected(q.answer);T.submit();assert.equal(T.state.stats[q.id].right,1);T.submit();assert.equal(T.state.stats[q.id].right,1,'重复提交不重复计数');T.action('star');assert.equal(T.state.stats[q.id].star,true);T.next();assert.notEqual(T.current().id,q.id);assert(storage.get('shizhi.v1'));
T.setMode('exam');T.startSession();q=T.current();T.setSelected(q.answer);T.action('save-answer');T.finish();assert(T.state.session.finished);assert.equal(Object.values(T.state.session.responses).filter(r=>r.ok).length,1);assert.equal(Object.values(T.state.session.responses).filter(r=>r.ok===false).length,1,'未答题交卷计错');
T.setMode('loop');T.setConfig({dept:'必考题',from:34,to:34,count:1});T.startSession();q=T.current();assert.equal(q.type,'判断');T.setSelected([]);T.submit(false);assert.equal(T.state.stats[q.id].wrong,1);T.next();assert(T.state.session.waiting);T.action('reinforce');T.submit(true);assert.equal(T.state.stats[q.id].stage,0,'提前加练不推进');T.next();clock+=61000;T.action('loop-check');assert(!T.state.session.waiting);T.submit(true);assert.equal(T.state.stats[q.id].stage,1);assert(T.state.loopPlans.length);T.finish();
const backup=JSON.parse(JSON.stringify({app:'shizhi',version:1,data:T.state}));const restored=T.validateBackup(backup);assert.equal(restored.loopPlans.length,T.state.loopPlans.length);assert.equal(restored.stats[q.id].stage,1);assert.throws(()=>T.validateBackup({app:'x',version:1,data:{}}));const invalid=JSON.parse(JSON.stringify(backup));invalid.data.stats[q.id].right=-1;assert.throws(()=>T.validateBackup(invalid));
T.setMode('memorize');T.startSession();const before=JSON.stringify(T.state.stats);T.next();assert.equal(JSON.stringify(T.state.stats),before,'背题不计次');
T.setMode('flash');T.startSession();q=T.current();T.action('flip');assert(els['#app'].innerHTML.includes('记住了'));T.submit(true);assert(T.state.stats[q.id].selfAssessed);T.finish();
for(const mode of ['game','sprint','random','weak','mistakes','favorites','department','review']){T.setMode(mode);T.setConfig({dept:'全部',from:1,to:1352,count:3});if(T.pool().length){T.startSession();T.render();assert(els['#app'].innerHTML.includes('question-panel')||els['#app'].innerHTML.includes('本轮回顾'));T.finish();}}
for(const theme of ctx.SHIZHI_THEMES){T.state.prefs.theme=theme.id;T.setView('themes');T.render();}
console.log('PASS: 7 页面渲染、13 模式选题/流程、统计防重复、考试漏答、循环等待/恢复、收藏、闪卡自评、背题、26 皮肤、备份校验与循环计划恢复');
